### ISSUE TITLE
Failing: cider.draw_most_frequent_scaffolds(testdict, graph_framework=True, number_of_structures=8, structures_per_row=4)

### ISSUE THREAD

**Issue by Kohulan** [hannbus/ChemIcal_DatasEt_compaRator#53]
@hannbus, As we discussed today in the meeting apparently this function fails.

```
2023-03-10 11:37:30,722 [ERROR] CIDER: An Error occured while executing CIDER!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_79681/1434904516.py", line 1, in <module>
    cider.draw_most_frequent_scaffolds(testdict, graph_framework=True, number_of_structures=8, structures_per_row=4)
  File "/home/kohulan/.local/lib/python3.10/site-packages/CIDER/cider.py", line 1489, in draw_most_frequent_scaffolds
    scaffolds = self._get_scaffold(
  File "/home/kohulan/.local/lib/python3.10/site-packages/CIDER/cider.py", line 1424, in _get_scaffold
    graph_framework_list.append(MurckoScaffold.MakeScaffoldGeneric(mol))
  File "/home/kohulan/.local/lib/python3.10/site-packages/rdkit/Chem/Scaffolds/MurckoScaffold.py", line 47, in MakeScaffoldGeneric
    return Chem.RemoveHs(res)
rdkit.Chem.rdchem.AtomValenceException: Explicit valence for atom # 40 C, 5, is greater than permitted
[11:37:30] Explicit valence for atom # 40 C, 5, is greater than permitted
---------------------------------------------------------------------------
AtomValenceException                      Traceback (most recent call last)
Cell In [32], line 1
----> 1 cider.draw_most_frequent_scaffolds(testdict, graph_framework=True, number_of_structures=8, structures_per_row=4)

File ~/.local/lib/python3.10/site-packages/CIDER/cider.py:1489, in ChemicalDatasetComparator.draw_most_frequent_scaffolds(self, all_dicts, number_of_structures, structures_per_row, image_size, framework, graph_framework, normalize, data_type, figsize, fontsize_title, fontsize_subtitle)
   1487     continue
   1488 title_list.append(single_dict)
-> 1489 scaffolds = self._get_scaffold(
   1490     all_dicts[single_dict][self.import_keyname],
   1491     number_of_structures,
   1492     structures_per_row,
   1493     image_size,
   1494     framework,
   1495     graph_framework,
   1496     normalize,
   1497 )
   1498 image_list.append(scaffolds[0])
   1499 all_dicts[single_dict][self.scaffold_list_keyname] = scaffolds[1]

File ~/.local/lib/python3.10/site-packages/CIDER/cider.py:1424, in ChemicalDatasetComparator._get_scaffold(self, moleculeset, number_of_structures, structures_per_row, image_size, framework, graph_framework, normalize)
   1422 graph_framework_list = []
   1423 for mol in framework_list:
-> 1424     graph_framework_list.append(MurckoScaffold.MakeScaffoldGeneric(mol))
   1425 for mol in graph_framework_list:
   1426     structure_list.append(Chem.MolToSmiles(mol))

File ~/.local/lib/python3.10/site-packages/rdkit/Chem/Scaffolds/MurckoScaffold.py:47, in MakeScaffoldGeneric(mol)
     45   bond.SetBondType(Chem.BondType.SINGLE)
     46   bond.SetIsAromatic(False)
---> 47 return Chem.RemoveHs(res)

AtomValenceException: Explicit valence for atom # 40 C, 5, is greater than permitted
```

**Comment by JonasSchaub** [comment]
Since the problem seems to be a generated scaffold, there is probably not much more possible than just catching the error on our side.
